In [34]:
import pandas as pd

In [35]:
df = pd.read_excel("CorporateSalary.xlsx")
df.head(2)

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200

In [36]:
# Split the data in to X and y
y = df[['Salary']]
print(y.head(2))
X = df.drop('Salary',axis=1)
X.head(2)

   Salary
0  119300
1  212200

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6
1,Director,Master's,Marketing,6.9,13,4.3

# Perform Train and test split

In [37]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_true, y_test_true = train_test_split(X,y,test_size=0.2,random_state=42)

In [38]:

OneHot_columns = ['Department']

ordinal_columns = ['Designation','Education']
numberical_cols = ['TenureYears','ProjectsCompleted','PerformanceScore']

Designation_Ord = ['Junior Analyst','Senior Analyst', 'Lead Consultant','Manager', 'Senior Manager','Director' ]
Education_Ord = ["Bachelor's", "Master's", 'PhD']

In [39]:
# Encoding AND Escaling

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler

# OrdinalEncoding_01 = (Name_Cat,OrdinalEncoder(categories=[Col_1_Order, Col_2_Order]),Ordinal_Col_Name,)
# OneHotEncoding_01 =  (NameOFcAT,OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),OneHot_Col_Name,)
# Scaling = ("num", StandardScaler(), Scaling_Col_Name)

OrdinalEncoding_01 = ("Orinal_Cols",OrdinalEncoder(categories=[Designation_Ord, Education_Ord]),ordinal_columns,)
OneHotEncoding_01 =  ("One_Hot_Cols",OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),OneHot_columns,)

Scaling = ("Scaling_01", StandardScaler(), numberical_cols)

transform_engine = ColumnTransformer(transformers=[OrdinalEncoding_01,OneHotEncoding_01,Scaling]).set_output(transform="pandas")

In [40]:
df.head(2)

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200

In [41]:
X_train_Trans = transform_engine.fit_transform(X_train)
X_train_Trans

,Orinal_Cols__Designation,Orinal_Cols__Education,One_Hot_Cols__Department_Engineering,One_Hot_Cols__Department_HR,One_Hot_Cols__Department_Marketing,One_Hot_Cols__Department_Product,One_Hot_Cols__Department_Sales,Scaling_01__TenureYears,Scaling_01__ProjectsCompleted,Scaling_01__PerformanceScore
55,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.435594,-0.525750,-0.977149
88,4.0,1.0,0.0,1.0,0.0,0.0,0.0,1.493033,-0.028978,-0.344690
26,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.143236,-1.188113,0.034785
42,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.201392,1.792519,-0.218198
69,5.0,1.0,0.0,0.0,0.0,1.0,0.0,1.607909,1.295747,1.046719
...,...,...,...,...,...,...,...,...,...,...
60,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.775056,0.302203,-1.609607
71,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.579908,-1.353704,1.173211
14,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.551189,1.130156,-0.091707
92,3.0,2.0,0.0,0.0,1.0,0.0,0.0,0.602741,0.798975,0.920227
51,3.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.172673,1.130156,1.173211

In [42]:
# Save Tranfomer in to pickle File
import joblib
joblib.dump(transform_engine,"transform.pkl")

['transform.pkl']

In [43]:
# pip3 install -U scikit-learn
# pip install sklearn

In [44]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: scikit-learn in c:\users\shivraj shinde\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (1.24.4)
Requirement already satisfied: scipy>=1.3.2 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)

ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\commands\install.py", line 584, in _determine_conflicts
    return check_install_conflicts(to_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\operations\check.py", line 117, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\operations\check.py", line 59, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dependencies)
                                       ^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\metadata\importlib\_dists.py", line 168, in version
    return parse_version(self._dist.version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 200, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[notice] A new release of pip is available: 24.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
                                                      ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\metadata\importlib\_dists.py", line 168, in version
    return parse_version(self._dist.version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 200, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

In [45]:
# Trainig Phase

from sklearn.linear_model import LinearRegression

linearmodel = LinearRegression()

linearmodel.fit(X_train_Trans,y_train_true)

joblib.dump(linearmodel,"linearModel.pkl")

['linearModel.pkl']

In [46]:
y_train_true

    Salary
55  182800
88  184500
26   93200
42   78100
69  235200
..     ...
60  119900
71   72100
14   76900
92  168900
51  149700

[80 rows x 1 columns]

In [47]:

y_train_pred = linearmodel.predict(X_train_Trans)

In [48]:
import numpy as np
# calcualte Error
# MSE
# MAE
# RMSE


from sklearn import metrics
mse = metrics.mean_squared_error(y_train_true,y_train_pred)
mae = metrics.mean_absolute_error(y_train_true,y_train_pred)
rmse = np.sqrt(mse)

print('Training')
print("Train_MSE:", mse)
print("Train_MAE:",mae)
print("Train_RMSE:",mae)

Training
Train_MSE: 22721164.447305653
Train_MAE: 3480.826125863011
Train_RMSE: 3480.826125863011

In [84]:
#  r2, ar2 % how good is the model 0 to 1
# 0 bad model
# 1 then good
# 0.85 0.87 0.89.

r2_score = metrics.r2_score(y_train_true,y_train_pred)
new_R2 = float(r2_score)

new_R2

0.9838701665731299

In [85]:
import numpy as np
from sklearn.metrics import r2_score

n = len(y_train_pred)  # number of observations
p = len(y_train_pred[0]) if len(y_train_true.shape) > 1 else 1  # number of features
adj_r2 = 1 - (1 - new_R2) * (n - 1) / (n - p - 1)


adj_r2

0.983663373836888

0.9838701665731299

In [52]:
# Tesing Phase

In [53]:
import joblib

transformer_obj = joblib.load("transform.pkl")
X_test_transform = transformer_obj.transform(X_test)

X_test_transform

,Orinal_Cols__Designation,Orinal_Cols__Education,One_Hot_Cols__Department_Engineering,One_Hot_Cols__Department_HR,One_Hot_Cols__Department_Marketing,One_Hot_Cols__Department_Product,One_Hot_Cols__Department_Sales,Scaling_01__TenureYears,Scaling_01__ProjectsCompleted,Scaling_01__PerformanceScore
83,0.0,2.0,1.0,0.0,0.0,0.0,0.0,0.028360,1.792519,0.034785
53,4.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.321436,-1.353704,-0.471182
70,3.0,1.0,0.0,0.0,0.0,1.0,0.0,-1.062965,1.461338,0.793736
45,2.0,0.0,0.0,0.0,0.0,0.0,1.0,-1.034245,0.798975,-0.471182
44,1.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.804493,-0.525750,0.287769
39,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.717618,0.798975,-1.609607
22,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.205842,-1.353704,-1.483116
80,4.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.775774,0.302203,0.667244
10,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.407593,0.798975,0.540752
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.717618,-0.194569,0.793736
18,1.0,2.0,0.0,0.0,1.0,0.0,0.0,-0.546021,1.461338,-0.344690
30,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.550471,-1.519294,0.920227
73,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.033527,1.792519,0.034785
33,4.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.005526,0.964566,-1.862591
90,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.459146,-0.360160,-0.977149
4,0.0,2.0,0.0,1.0,0.0,0.0,0.0,-0.804493,0.302203,1.299703
76,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.516584,0.136612,0.920227
77,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.465031,1.461338,-1.736099
12,3.0,2.0,0.0,0.0,0.0,1.0,0.0,-1.465031,-0.360160,-1.609607
31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.115235,0.633384,-1.103640

In [54]:
Liner_Model = joblib.load("linearModel.pkl")

y_test_pred = Liner_Model.predict(X_test_transform)

y_test_pred

array([[112372.72805871],
       [157452.10698926],
       [156563.45624616],
       [116076.3221174 ],
       [ 91508.57222522],
       [120200.94043528],
       [115877.18766996],
       [173587.50091765],
       [ 68228.31484991],
       [118401.44832316],
       [116206.49928137],
       [144481.58796352],
       [166231.60089184],
       [157801.15388733],
       [ 75677.42720386],
       [ 87440.87476099],
       [171325.69261281],
       [ 77801.8864807 ],
       [152504.95292542],
       [ 88250.49049462]])

In [55]:
y_test_true

    Salary
83  109400
53  155300
70  153200
45  115100
44   93400
39  115300
22  110600
80  169900
10   71300
0   119300
18  117100
30  142400
73  163400
33  157800
90   76700
4    90100
76  167400
77   77000
12  146000
31   92900

In [56]:
from sklearn import metrics
mse = metrics.mean_squared_error(y_test_true,y_test_pred)
mae = metrics.mean_absolute_error(y_test_true,y_test_pred)

rmse = np.sqrt(mse)

print('Training')
print("Train_MSE:", mse)
print("Train_MAE:",mae)
print("Train_RMSE:",mae)

Training
Train_MSE: 10313640.389216509
Train_MAE: 2728.1745028454416
Train_RMSE: 2728.1745028454416

In [57]:
r2_score = metrics.r2_score(y_test_true,y_test_pred)
print(r2_score)

0.9897720148948451

In [ ]:


n = len(y_test_pred)  # number of observations
p = len(y_test_pred[0]) if len(y_test_true.shape) > 1 else 1  # number of features
adj_r2 = 1 - (1 - r2_score) * (n - 1) / (n - p - 1)
adj_r2

0.9892037935001143