In [44]:
import pandas as pd

In [45]:
df = pd.read_excel("Data_Raw\CorporateSalary.xlsx")

In [46]:
# Split data in to X AND y

y = df['Salary']
y

X = df.drop('Salary',axis=1)
X

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6
1,Director,Master's,Marketing,6.9,13,4.3
2,Manager,Bachelor's,Engineering,3.9,14,2.7
3,Lead Consultant,Master's,Data Science,5.3,13,2.7
4,Junior Analyst,PhD,HR,3.4,15,5.0
...,...,...,...,...,...,...
115,Director,PhD,HR,0.4,1,2.3
116,Senior Manager,Master's,Data Science,0.2,0,2.1
117,Junior Analyst,Bachelor's,Engineering,0.0,1,1.9
118,Manager,Master's,Sales,0.2,2,2.0
119,Lead Consultant,Bachelor's,Marketing,0.3,1,2.2

In [47]:
# Train and Test SPlit
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_true, y_test_true = train_test_split(X,y,test_size=0.20,random_state=42)

X_train

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore
42,Junior Analyst,Bachelor's,HR,5.5,24,3.8
12,Manager,PhD,Product,1.1,11,2.7
15,Junior Analyst,PhD,Sales,7.2,10,3.6
114,Lead Consultant,Master's,Product,0.1,2,2.0
76,Manager,Master's,Engineering,8.0,14,4.7
...,...,...,...,...,...,...
106,Junior Analyst,Bachelor's,Engineering,0.1,40,5.0
14,Junior Analyst,Master's,HR,0.8,20,3.9
92,Manager,PhD,Marketing,8.3,18,4.7
51,Manager,Bachelor's,Product,5.6,20,4.9
102,Senior Analyst,Master's,Sales,15.2,2,2.5

In [48]:
X_train.to_excel("Data_Train_Test_Split\X_train.xlsx",index=False)
y_train_true.to_excel("Data_Train_Test_Split\y_train_true.xlsx",index=False)

In [49]:
X_test.to_excel("Data_Train_Test_Split\X_test.xlsx",index=False)
y_test_true.to_excel("Data_Train_Test_Split\y_test_true.xlsx",index=False)

In [50]:
# Transformation 
Numerica_Colums = ['TenureYears','ProjectsCompleted','PerformanceScore']
Ordered_Columns = ['Designation', 'Education']
One_Hot_Columns = ['Department']

Designation_Order = ['Junior Analyst', 'Senior Analyst', 'Lead Consultant', 'Manager', 'Senior Manager','Director']
Education_Order = ["Bachelor's", "Master's", 'PhD']

In [51]:
# Transformation Actual Process
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder, StandardScaler


OrdinalEncoding_01 = ("Oridnal_Encoder",OrdinalEncoder(categories=[Designation_Order, Education_Order]),Ordered_Columns,)
OneHotEncoding_01 =  ("One_Hot_Encoder",OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),One_Hot_Columns,)
Scaling = ("Numerical_Coluns", StandardScaler(), Numerica_Colums)

transformer_engine = ColumnTransformer(transformers=[OrdinalEncoding_01,OneHotEncoding_01,Scaling]).set_output(transform="pandas")

transformer_engine

ColumnTransformer(transformers=[('Oridnal_Encoder',
                                 OrdinalEncoder(categories=[['Junior Analyst',
                                                             'Senior Analyst',
                                                             'Lead Consultant',
                                                             'Manager',
                                                             'Senior Manager',
                                                             'Director'],
                                                            ["Bachelor's",
                                                             "Master's",
                                                             'PhD']]),
                                 ['Designation', 'Education']),
                                ('One_Hot_Encoder',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore',
                                               sparse_output=False),
                                 ['Department']),
                                ('Numerical_Coluns', StandardScaler(),
                                 ['TenureYears', 'ProjectsCompleted',
                                  'PerformanceScore'])])

In [52]:
X_train_Transform = transformer_engine.fit_transform(X_train)

X_train_Transform.head(2)

,Oridnal_Encoder__Designation,Oridnal_Encoder__Education,One_Hot_Encoder__Department_Engineering,One_Hot_Encoder__Department_HR,One_Hot_Encoder__Department_Marketing,One_Hot_Encoder__Department_Product,One_Hot_Encoder__Department_Sales,Numerical_Coluns__TenureYears,Numerical_Coluns__ProjectsCompleted,Numerical_Coluns__PerformanceScore
42,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.058633,1.084800,0.063193
12,3.0,2.0,0.0,0.0,0.0,1.0,0.0,-1.049288,-0.200889,-1.030770

In [53]:

import joblib
joblib.dump(transformer_engine,"TransFile/transform.pkl")

['TransFile/transform.pkl']

In [54]:
# Save Train Data to Excel 
X_train_Transform.to_excel("Data_Transformed\X_Train_Trans.xlsx",index=False)

In [55]:
Transform_File = joblib.load("TransFile/transform.pkl")
X_test_tranform = Transform_File.fit_transform(X_test)

In [56]:
# Save Test Data to Excel 
X_test_tranform.to_excel("Data_Transformed\X_Test_Trans.xlsx",index=False)