In [119]:
import pandas as pd

In [120]:
df = pd.read_excel("CorporateSalary.xlsx")
df.head(2)
df.shape

(120, 7)

In [121]:
sns.boxplot(x=df['Salary'])

In [122]:
df_y = df['Salary']

Q1 = df_y.quantile(0.25)
Q2 = df_y.quantile(0.50)
Q3 = df_y.quantile(0.75)
Q4 = df_y.quantile(0.1)
print(Q1,Q2,Q3,Q4)


IQR = Q3-Q1
print(IQR)

lower_Limit = Q1 - 1.5 *IQR

print(lower_Limit)

Higher_Limit = Q3 + 1.5 *IQR

Higher_Limit

93175.0 117450.0 151075.0 71240.0
57900.0
6325.0

237925.0

In [123]:
drop_Higher_Limit = df[df['Salary']>=Higher_Limit].index
df_No_Outlier = df.drop(drop_Higher_Limit,axis=0)

In [124]:
df_No_Outlier
df_No_Outlier.shape

(111, 7)

In [125]:
index_outliers = df_No_Outlier[df_No_Outlier['Salary']<=lower_Limit].index

In [126]:
df_No_Outlier = df_No_Outlier.drop(index_outliers,axis=0)

df_No_Outlier

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200
2,Manager,Bachelor's,Engineering,3.9,14,2.7,139400
3,Lead Consultant,Master's,Data Science,5.3,13,2.7,137200
4,Junior Analyst,PhD,HR,3.4,15,5.0,90100
...,...,...,...,...,...,...,...
115,Director,PhD,HR,0.4,1,2.3,90000
116,Senior Manager,Master's,Data Science,0.2,0,2.1,80000
117,Junior Analyst,Bachelor's,Engineering,0.0,1,1.9,25000
118,Manager,Master's,Sales,0.2,2,2.0,65000
119,Lead Consultant,Bachelor's,Marketing,0.3,1,2.2,58000

In [127]:
# Split the data in to X and y
y = df_No_Outlier[['Salary']]
print(y.head(2))
X = df_No_Outlier.drop('Salary',axis=1)
X.head(2)

   Salary
0  119300
1  212200

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6
1,Director,Master's,Marketing,6.9,13,4.3

# Perform Train and test split

In [128]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_true, y_test_true = train_test_split(X,y,test_size=0.2,random_state=42)

In [129]:

OneHot_columns = ['Department']

ordinal_columns = ['Designation','Education']
numberical_cols = ['TenureYears','ProjectsCompleted','PerformanceScore']

Designation_Ord = ['Junior Analyst','Senior Analyst', 'Lead Consultant','Manager', 'Senior Manager','Director' ]
Education_Ord = ["Bachelor's", "Master's", 'PhD']

In [130]:
# Encoding AND Escaling

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler

# OrdinalEncoding_01 = (Name_Cat,OrdinalEncoder(categories=[Col_1_Order, Col_2_Order]),Ordinal_Col_Name,)
# OneHotEncoding_01 =  (NameOFcAT,OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),OneHot_Col_Name,)
# Scaling = ("num", StandardScaler(), Scaling_Col_Name)

OrdinalEncoding_01 = ("Orinal_Cols",OrdinalEncoder(categories=[Designation_Ord, Education_Ord]),ordinal_columns,)
OneHotEncoding_01 =  ("One_Hot_Cols",OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),OneHot_columns,)

Scaling = ("Scaling_01", StandardScaler(), numberical_cols)

transform_engine = ColumnTransformer(transformers=[OrdinalEncoding_01,OneHotEncoding_01,Scaling]).set_output(transform="pandas")

In [131]:
df.head(2)

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200

In [132]:
X_train_Trans = transform_engine.fit_transform(X_train)
X_train_Trans

,Orinal_Cols__Designation,Orinal_Cols__Education,One_Hot_Cols__Department_Engineering,One_Hot_Cols__Department_HR,One_Hot_Cols__Department_Marketing,One_Hot_Cols__Department_Product,One_Hot_Cols__Department_Sales,Scaling_01__TenureYears,Scaling_01__ProjectsCompleted,Scaling_01__PerformanceScore
26,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.315603,-0.860290,0.319101
22,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.288713,-0.994283,-0.928938
31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.078901,0.613623,-0.616928
47,2.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.026300,1.149592,0.319101
77,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.157212,1.283584,-1.136944
...,...,...,...,...,...,...,...,...,...,...
115,5.0,2.0,0.0,1.0,0.0,0.0,0.0,-1.341314,-1.530251,-1.448954
14,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.236113,1.015600,0.215098
93,2.0,1.0,0.0,0.0,0.0,0.0,1.0,0.420804,-0.726298,0.839117
52,4.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.578606,0.747615,1.047123
111,0.0,1.0,0.0,0.0,0.0,0.0,1.0,-1.420215,-1.530251,-1.760964

In [133]:
# Save Tranfomer in to pickle File
import joblib
joblib.dump(transform_engine,"transform.pkl")

['transform.pkl']

In [134]:
# pip3 install -U scikit-learn
# pip install sklearn

In [135]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\shivraj shinde\anaconda3\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (1.24.4)
Requirement already satisfied: scipy>=1.3.2 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\shivraj shinde\anaconda3\lib\site-packages (from scikit-learn) (2.2.0)
Note: you may need to restart the kernel to use updated packages.

ERROR: Error while checking for conflicts. Please file an issue on pip's issue tracker: https://github.com/pypa/pip/issues/new
Traceback (most recent call last):
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\commands\install.py", line 584, in _determine_conflicts
    return check_install_conflicts(to_install)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\operations\check.py", line 117, in check_install_conflicts
    package_set, _ = create_package_set_from_installed()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\operations\check.py", line 59, in create_package_set_from_installed
    package_set[name] = PackageDetails(dist.version, dependencies)
                                       ^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\metadata\importlib\_dists.py", line 168, in version
    return parse_version(self._dist.version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 200, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

[notice] A new release of pip is available: 24.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: Exception:
Traceback (most recent call last):
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\commands\install.py", line 483, in run
    installed_versions[distribution.canonical_name] = distribution.version
                                                      ^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_internal\metadata\importlib\_dists.py", line 168, in version
    return parse_version(self._dist.version)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\SHIVRAJ SHINDE\anaconda3\Lib\site-packages\pip\_vendor\packaging\version.py", line 200, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

In [136]:
# Trainig Phase

from sklearn.linear_model import LinearRegression

linearmodel = LinearRegression()

linearmodel.fit(X_train_Trans,y_train_true)

joblib.dump(linearmodel,"linearModel.pkl")

['linearModel.pkl']

In [137]:
y_train_true

     Salary
26    93200
22   110600
31    92900
47   126400
77    77000
..      ...
115   90000
14    76900
93   133300
52   171800
111   32500

[88 rows x 1 columns]

In [138]:

y_train_pred = linearmodel.predict(X_train_Trans)

In [139]:
import numpy as np
# calcualte Error
# MSE
# MAE
# RMSE


from sklearn import metrics
mse = metrics.mean_squared_error(y_train_true,y_train_pred)
mae = metrics.mean_absolute_error(y_train_true,y_train_pred)
rmse = np.sqrt(mse)

print('Training')
print("Train_MSE:", mse)
print("Train_MAE:",mae)
print("Train_RMSE:",mae)

Training
Train_MSE: 212523144.42078608
Train_MAE: 9447.451776073482
Train_RMSE: 9447.451776073482

In [140]:
#  r2, ar2 % how good is the model 0 to 1
# 0 bad model
# 1 then good
# 0.85 0.87 0.89.

r2_score = metrics.r2_score(y_train_true,y_train_pred)
new_R2 = float(r2_score)

new_R2

0.8621388540314092

In [141]:
import numpy as np
from sklearn.metrics import r2_score

n = len(y_train_pred)  # number of observations
p = len(y_train_pred[0]) if len(y_train_true.shape) > 1 else 1  # number of features
adj_r2 = 1 - (1 - new_R2) * (n - 1) / (n - p - 1)


adj_r2

0.8605358174503791

In [142]:
# Tesing Phase

In [143]:
import joblib

transformer_obj = joblib.load("transform.pkl")
X_test_transform = transformer_obj.transform(X_test)

X_test_transform

,Orinal_Cols__Designation,Orinal_Cols__Education,One_Hot_Cols__Department_Engineering,One_Hot_Cols__Department_HR,One_Hot_Cols__Department_Marketing,One_Hot_Cols__Department_Product,One_Hot_Cols__Department_Sales,Scaling_01__TenureYears,Scaling_01__ProjectsCompleted,Scaling_01__PerformanceScore
79,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.367614,-0.592306,-0.304919
10,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.104611,0.747615,0.735114
4,0.0,2.0,0.0,1.0,0.0,0.0,0.0,-0.552306,0.345639,1.359133
85,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.762708,-0.056338,1.255130
65,2.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.289303,1.283584,-0.408922
69,5.0,1.0,0.0,0.0,0.0,1.0,0.0,1.656917,1.149592,1.151127
30,2.0,0.0,1.0,0.0,0.0,0.0,0.0,1.604317,-1.128275,1.047123
45,2.0,0.0,0.0,0.0,0.0,0.0,1.0,-0.762708,0.747615,-0.096912
97,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.578606,-0.458314,0.735114
11,5.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.105201,-0.458314,-0.304919
80,4.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.526005,0.345639,0.839117
81,2.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.262413,-0.860290,1.359133
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.841609,-0.056338,0.943120
82,1.0,2.0,0.0,0.0,0.0,0.0,1.0,1.499115,-1.128275,-0.824935
18,1.0,2.0,0.0,0.0,1.0,0.0,0.0,-0.315603,1.283584,0.007091
71,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.262413,-0.994283,1.255130
57,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.236702,0.077655,0.007091
73,3.0,0.0,0.0,0.0,0.0,1.0,0.0,1.130912,1.551568,0.319101
118,3.0,1.0,0.0,0.0,0.0,0.0,1.0,-1.393914,-1.396259,-1.760964
42,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.000000,1.551568,0.111094
12,3.0,2.0,0.0,0.0,0.0,1.0,0.0,-1.157212,-0.190330,-1.032941
36,1.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.894209,1.551568,1.047123
66,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.025711,-0.860290,0.839117

In [144]:
Liner_Model = joblib.load("linearModel.pkl")

y_test_pred = Liner_Model.predict(X_test_transform)

y_test_pred

array([[ 97979.89884983],
       [ 74704.77665935],
       [ 91158.76048129],
       [120317.28175056],
       [120151.18169295],
       [230731.47353802],
       [140735.32851532],
       [105722.1339008 ],
       [119868.23302764],
       [165450.13174364],
       [157394.30171426],
       [101746.70144026],
       [131265.60757926],
       [108686.49728845],
       [114367.57851765],
       [ 62394.18466857],
       [ 88610.54760625],
       [175619.85494637],
       [ 86731.54217642],
       [ 88335.91852402],
       [124150.48197641],
       [107408.04538827],
       [ 62760.08299608]])

In [145]:
y_test_true

     Salary
79    92700
10    71300
4     90100
85   111100
65   121100
69   235200
30   142400
45   115100
97   126200
11   212200
80   169900
81   104700
0    119300
82   121700
18   117100
71    72100
57    98000
73   163400
118   65000
42    78100
12   146000
36   101600
66    70700

In [146]:
from sklearn import metrics
mse = metrics.mean_squared_error(y_test_true,y_test_pred)
mae = metrics.mean_absolute_error(y_test_true,y_test_pred)

rmse = np.sqrt(mse)

print('Training')
print("Train_MSE:", mse)
print("Train_MAE:",mae)
print("Train_RMSE:",mae)

Training
Train_MSE: 192642705.64648762
Train_MAE: 10024.035988219679
Train_RMSE: 10024.035988219679

In [147]:
r2_score = metrics.r2_score(y_test_true,y_test_pred)
print(r2_score)

0.8946086627130138

In [148]:


n = len(y_test_pred)  # number of observations
p = len(y_test_pred[0]) if len(y_test_true.shape) > 1 else 1  # number of features
adj_r2 = 1 - (1 - r2_score) * (n - 1) / (n - p - 1)
adj_r2

0.8895900276041097