In [2]:
import pandas as pd

In [3]:
df = pd.read_excel("CorporateSalary.xlsx")
df.head(2)

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200

In [4]:
# Split the data in to X and y
y = df[['Salary']]
print(y.head(2))
X = df.drop('Salary',axis=1)
X.head(2)

   Salary
0  119300
1  212200

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6
1,Director,Master's,Marketing,6.9,13,4.3

# Perform Train and test split

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train_true, y_test_true = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
OneHot_columns = ['Department']

ordinal_columns = ['Designation','Education']
numberical_cols = ['TenureYears','ProjectsCompleted','PerformanceScore']

Designation_Ord = ['Junior Analyst','Senior Analyst', 'Lead Consultant','Manager', 'Senior Manager','Director' ]
Education_Ord = ["Bachelor's", "Master's", 'PhD']

In [7]:
# Encoding AND Escaling

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder, StandardScaler

# OrdinalEncoding_01 = (Name_Cat,OrdinalEncoder(categories=[Col_1_Order, Col_2_Order]),Ordinal_Col_Name,)
# OneHotEncoding_01 =  (NameOFcAT,OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),OneHot_Col_Name,)
# Scaling = ("num", StandardScaler(), Scaling_Col_Name)

OrdinalEncoding_01 = ("Orinal_Cols",OrdinalEncoder(categories=[Designation_Ord, Education_Ord]),ordinal_columns,)
OneHotEncoding_01 =  ("One_Hot_Cols",OneHotEncoder(sparse_output=False, drop="first", handle_unknown="ignore"),OneHot_columns,)

Scaling = ("Scaling_01", StandardScaler(), numberical_cols)

transform_engine = ColumnTransformer(transformers=[OrdinalEncoding_01,OneHotEncoding_01,Scaling]).set_output(transform="pandas")

In [8]:
df.head(2)

,Designation,Education,Department,TenureYears,ProjectsCompleted,PerformanceScore,Salary
0,Senior Analyst,Bachelor's,Data Science,8.7,12,4.6,119300
1,Director,Master's,Marketing,6.9,13,4.3,212200

In [9]:
X_train_Trans = transform_engine.fit_transform(X_train)
X_train_Trans

,Orinal_Cols__Designation,Orinal_Cols__Education,One_Hot_Cols__Department_Engineering,One_Hot_Cols__Department_HR,One_Hot_Cols__Department_Marketing,One_Hot_Cols__Department_Product,One_Hot_Cols__Department_Sales,Scaling_01__TenureYears,Scaling_01__ProjectsCompleted,Scaling_01__PerformanceScore
42,0.0,0.0,0.0,1.0,0.0,0.0,0.0,-0.058633,1.084800,0.063193
12,3.0,2.0,0.0,0.0,0.0,1.0,0.0,-1.049288,-0.200889,-1.030770
15,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.324121,-0.299788,-0.135709
114,2.0,1.0,0.0,0.0,0.0,1.0,0.0,-1.274436,-1.090981,-1.726929
76,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.504240,0.095809,0.958254
...,...,...,...,...,...,...,...,...,...,...
106,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-1.274436,2.667186,1.256608
14,0.0,1.0,0.0,1.0,0.0,0.0,0.0,-1.116832,0.689203,0.162644
92,3.0,2.0,0.0,0.0,1.0,0.0,0.0,0.571784,0.491405,0.958254
51,3.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.036118,0.689203,1.157156
102,1.0,1.0,0.0,0.0,0.0,0.0,1.0,2.125311,-1.090981,-1.229673

In [10]:
# Save Tranfomer in to pickle File
import joblib
joblib.dump(transform_engine,"transform.pkl")

['transform.pkl']

In [11]:
# pip3 install -U scikit-learn
# pip install sklearn

In [14]:
# pip install scikit-learn

In [ ]:
# Trainig Phase

from sklearn.linear_model import Ridge

Ridge_model = Ridge(alpha=0.01)

Ridge_model.fit(X_train_Trans,y_train_true)

joblib.dump(Ridge_model,"Ridge_model.pkl")

['Ridge_model.pkl']

In [33]:
from sklearn.linear_model import Lasso

Lasso_model = Lasso(alpha=0.01)

Lasso_model.fit(X_train_Trans,y_train_true)

joblib.dump(Lasso_model,"Lasso_model.pkl")

['Lasso_model.pkl']

In [21]:
y_train_true

     Salary
42    78100
12   146000
15    98500
114   60000
76   167400
..      ...
106   40000
14    76900
92   168900
51   149700
102   55000

[96 rows x 1 columns]

In [22]:

y_train_pred = Ridge_model.predict(X_train_Trans)

In [23]:
import numpy as np
# calcualte Error
# MSE
# MAE
# RMSE


from sklearn import metrics
mse = metrics.mean_squared_error(y_train_true,y_train_pred)
mae = metrics.mean_absolute_error(y_train_true,y_train_pred)
rmse = np.sqrt(mse)

print('Training')
print("Train_MSE:", mse)
print("Train_MAE:",mae)
print("Train_RMSE:",mae)

Training
Train_MSE: 1198962771.2312217
Train_MAE: 21820.951242180665
Train_RMSE: 21820.951242180665

In [25]:
#  r2, ar2 % how good is the model 0 to 1
# 0 bad model
# 1 then good
# 0.85 0.87 0.89.

r2_score = metrics.r2_score(y_train_true,y_train_pred)
new_R2 = float(r2_score)

new_R2

0.7679794150680583

In [26]:
import numpy as np
from sklearn.metrics import r2_score

n = len(y_train_pred)  # number of observations
p = len(y_train_pred[0]) if len(y_train_true.shape) > 1 else 1  # number of features
adj_r2 = 1 - (1 - new_R2) * (n - 1) / (n - p - 1)


adj_r2

0.7655111109730377

In [ ]:
# Tesing Phase

In [27]:
import joblib

transformer_obj = joblib.load("transform.pkl")
X_test_transform = transformer_obj.transform(X_test)

X_test_transform

,Orinal_Cols__Designation,Orinal_Cols__Education,One_Hot_Cols__Department_Engineering,One_Hot_Cols__Department_HR,One_Hot_Cols__Department_Marketing,One_Hot_Cols__Department_Product,One_Hot_Cols__Department_Sales,Scaling_01__TenureYears,Scaling_01__ProjectsCompleted,Scaling_01__PerformanceScore
44,1.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.531445,-0.299788,0.460998
47,2.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.081147,0.788103,0.262095
4,0.0,2.0,0.0,1.0,0.0,0.0,0.0,-0.531445,0.194708,1.256608
55,4.0,0.0,0.0,0.0,0.0,0.0,0.0,1.224716,-0.299788,-0.533514
26,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.211546,-0.695385,0.262095
64,1.0,0.0,0.0,0.0,0.0,1.0,0.0,-0.869168,0.392506,0.063193
73,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.909508,1.084800,0.262095
10,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.004258,0.491405,0.659900
40,0.0,2.0,0.0,0.0,0.0,1.0,0.0,-1.071802,1.084800,0.162644
107,5.0,1.0,0.0,0.0,0.0,0.0,1.0,3.498719,5.436362,1.256608
18,1.0,2.0,0.0,0.0,1.0,0.0,0.0,-0.328811,0.887002,-0.036258
62,3.0,1.0,0.0,0.0,0.0,1.0,0.0,0.279091,0.689203,1.256608
11,5.0,0.0,1.0,0.0,0.0,0.0,0.0,-0.148692,-0.398687,-0.334612
36,1.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.824139,1.084800,0.958254
89,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.067112,-0.299788,-0.235161
91,3.0,2.0,0.0,0.0,0.0,0.0,1.0,0.886993,-0.003091,-1.130222
109,2.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.229407,3.161682,1.157156
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.661844,-0.101990,0.858803
88,4.0,1.0,0.0,1.0,0.0,0.0,0.0,1.269746,-0.003091,-0.036258
104,2.0,2.0,0.0,0.0,0.0,1.0,0.0,3.160996,4.744068,1.157156
65,2.0,1.0,0.0,1.0,0.0,0.0,0.0,-0.306296,0.887002,-0.434063
45,2.0,0.0,0.0,0.0,0.0,0.0,1.0,-0.711564,0.491405,-0.135709
31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.008912,0.392506,-0.632966
70,3.0,1.0,0.0,0.0,0.0,1.0,0.0,-0.734079,0.887002,0.858803

In [28]:
Liner_Model = joblib.load("Ridge_model.pkl")

y_test_pred = Liner_Model.predict(X_test_transform)

y_test_pred

array([[ 92003.38543737],
       [157875.42155765],
       [ 89596.65337729],
       [207603.20204442],
       [ 71247.03266971],
       [ 98213.27635533],
       [213947.38689557],
       [ 84272.34839715],
       [100238.47320535],
       [474954.0549059 ],
       [140456.98929281],
       [193648.05751831],
       [178987.69942193],
       [129627.15189956],
       [118290.64959382],
       [171146.36498338],
       [223220.43606737],
       [138616.84129663],
       [210560.80541188],
       [381910.99632992],
       [151431.10738717],
       [122552.71054944],
       [106806.66405963],
       [171986.35738032]])

In [29]:
y_test_true

     Salary
44    93400
47   126400
4     90100
55   182800
26    93200
64    96800
73   163400
10    71300
40    94100
107  600000
18   117100
62   161000
11   212200
36   101600
89   112600
91   163900
109  350000
0    119300
88   184500
104  520000
65   121100
45   115100
31    92900
70   153200

In [30]:
from sklearn import metrics
mse = metrics.mean_squared_error(y_test_true,y_test_pred)
mae = metrics.mean_absolute_error(y_test_true,y_test_pred)

rmse = np.sqrt(mse)

print('Training')
print("Train_MSE:", mse)
print("Train_MAE:",mae)
print("Train_RMSE:",mae)

Training
Train_MSE: 2574592443.8367257
Train_MAE: 32798.06456745465
Train_RMSE: 32798.06456745465

In [31]:
r2_score = metrics.r2_score(y_test_true,y_test_pred)
print(r2_score)

0.8485057218931836

In [32]:
# n = Number of test observations
n = X_test.shape[0]

# p = Number of predictor variables (features)
p = X_test.shape[1]

# Adjusted R²
adj_r2 = 1 - (1 - r2_score) * (n - 1) / (n - p - 1)

print("Adjusted R²:", adj_r2)

Adjusted R²: 0.7950371531496014