# Data Reading

In [65]:
import pandas as pd

def readFile():
     df = pd.read_csv("E:/1.Eathans/Ethans/Data/Airline/Airline1.csv")
     return df

#  Cleaning

In [66]:
df = pd.read_csv("E:/1.Eathans/Ethans/Data/Airline/Airline1.csv")

# Source,Destination,Route,Total_Stops,Price

In [67]:


def Handel_Missing(df):
    missin_COL = ['Source','Destination','Route','Total_Stops']
    for i in missin_COL:
        Missing = df[i].mode()[0]
        df.fillna({i:Missing},inplace=True)
        
    Missing_Price = df['Price'].mean()
    df.fillna({'Price':Missing_Price},inplace=True)
    return df
Handel_Missing(df)
df.isnull().sum()

ID                 0
Airline            0
Date_of_Journey    0
Source             0
Destination        0
Route              0
Dep_Time           0
Arrival_Time       0
Duration           0
Total_Stops        0
Additional_Info    0
Price              0
dtype: int64

# Handle Duplicates

In [68]:
def Handle_Duplicates(df):
    df.drop_duplicates(inplace=True)
    df[df.duplicated()]
    return df
Handle_Duplicates(df)

,ID,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,1,IndiGo,24-03-2019 22:20,Banglore,New Delhi,BLR _ DEL,22:20,25-03-2019 01:10,2h 50m,non-stop,No info,3897.0
1,2,Air India,01-05-2019 05:50,Kolkata,Banglore,CCU _ IXR _ BBI _ BLR,05:50,01-05-2019 13:15,7h 25m,2 stops,No info,7662.0
2,3,Jet Airways,09-06-2019 09:25,Delhi,Cochin,DEL _ LKO _ BOM _ COK,09:25,10-06-2019 04:25,19h 00m,2 stops,No info,13882.0
3,4,IndiGo,12-05-2019 18:05,Kolkata,Banglore,CCU _ NAG _ BLR,18:05,12-05-2019 23:30,5h 25m,1 stop,No info,6218.0
4,5,IndiGo,01-03-2019 16:50,Banglore,New Delhi,BLR _ NAG _ DEL,16:50,01-03-2019 21:35,4h 45m,1 stop,No info,13302.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10678,10679,Air Asia,09-04-2019 19:55,Kolkata,Banglore,CCU ? BLR,19:55,09-04-2019 22:25,2h 30m,non-stop,No info,4107.0
10679,10680,Air India,27-04-2019 20:45,Kolkata,Banglore,CCU ? BLR,20:45,27-04-2019 23:20,2h 35m,non-stop,No info,4145.0
10680,10681,Jet Airways,27-04-2019 08:20,Banglore,Delhi,BLR ? DEL,08:20,27-04-2019 11:20,3h 00m,non-stop,No info,7229.0
10681,10682,Vistara,01-03-2019 11:30,Banglore,New Delhi,BLR ? DEL,11:30,01-03-2019 14:10,2h 40m,non-stop,No info,12648.0
10682,10683,Air India,09-05-2019 10:55,Delhi,Cochin,DEL ? GOI ? BOM ? COK,10:55,09-05-2019 19:15,8h 20m,2 stops,No info,11753.0

In [69]:
df[df.duplicated()]

Empty DataFrame
Columns: [ID, Airline, Date_of_Journey, Source, Destination, Route, Dep_Time, Arrival_Time, Duration, Total_Stops, Additional_Info, Price]
Index: []

# Handle unever Values

In [70]:
df['Destination'].value_counts()
def Replace_Uneve(df):
    df['Destination'] = df['Destination'].replace({"New Delhi":"Delhi"})
    return df
Replace_Uneve(df)

df['Destination'].value_counts()

Destination
Cochin       4538
Banglore     2871
Delhi        2196
Hyderabad     697
Kolkata       381
Name: count, dtype: int64

In [71]:


def convertDur_Min(df):
    for i in df.index:
        ColOne = df.loc[i,'Duration'].split()[0]
        ColTwo = df.loc[i,'Duration'].split()[1]
        
        if "h" in ColOne:
            ColOne = int(ColOne.replace("h",""))*60
        elif "m" in ColOne:
            ColOne = int(ColOne.replace("m",""))

        if "h" in ColTwo:
            ColTwo = int(ColTwo.replace("h",""))*60
        elif "m" in ColTwo:
            ColTwo = int(ColTwo.replace("m",""))
        
        df.loc[i,'DurHrs_Mins'] = ColOne + ColTwo
    return df

In [72]:
def DateTimeConverion(df):
    df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'],format='mixed')
    df['D_day'] = df['Date_of_Journey'].dt.day
    df['D_month'] = df['Date_of_Journey'].dt.month
    df['D_year'] = df['Date_of_Journey'].dt.year
    df['D_hours'] = df['Date_of_Journey'].dt.hour
    df['D_minutes'] = df['Date_of_Journey'].dt.minute

    df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'],format='mixed')
    df['A_day'] = df['Arrival_Time'].dt.day
    df['A_month'] = df['Arrival_Time'].dt.month
    df['A_year'] = df['Arrival_Time'].dt.year
    df['A_hours'] = df['Arrival_Time'].dt.hour
    df['A_minutes'] = df['Arrival_Time'].dt.minute
    return df

In [ ]:
def uncessaryCol(df):
    col_Drop = ['ID','Date_of_Journey','Route','Dep_Time',
                'Arrival_Time','Duration','Additional_Info']
    df.drop(col_Drop,axis=1,inplace=True)
    return df

In [74]:
readFile()
df = Handel_Missing(df)
df = Handle_Duplicates(df)
df = Replace_Uneve(df)
df = convertDur_Min(df)
df = DateTimeConverion(df)
df = uncessaryCol(df)
df

,Airline,Source,Destination,Total_Stops,Price,DurHrs_Mins,D_day,D_month,D_year,D_hours,D_minutes,A_day,A_month,A_year,A_hours,A_minutes
0,IndiGo,Banglore,Delhi,non-stop,3897.0,170.0,24,3,2019,22,20,25,3,2019,1,10
1,Air India,Kolkata,Banglore,2 stops,7662.0,445.0,5,1,2019,5,50,5,1,2019,13,15
2,Jet Airways,Delhi,Cochin,2 stops,13882.0,1140.0,6,9,2019,9,25,6,10,2019,4,25
3,IndiGo,Kolkata,Banglore,1 stop,6218.0,325.0,5,12,2019,18,5,5,12,2019,23,30
4,IndiGo,Banglore,Delhi,1 stop,13302.0,285.0,3,1,2019,16,50,3,1,2019,21,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10678,Air Asia,Kolkata,Banglore,non-stop,4107.0,150.0,4,9,2019,19,55,4,9,2019,22,25
10679,Air India,Kolkata,Banglore,non-stop,4145.0,155.0,27,4,2019,20,45,27,4,2019,23,20
10680,Jet Airways,Banglore,Delhi,non-stop,7229.0,180.0,27,4,2019,8,20,27,4,2019,11,20
10681,Vistara,Banglore,Delhi,non-stop,12648.0,160.0,3,1,2019,11,30,3,1,2019,14,10
10682,Air India,Delhi,Cochin,2 stops,11753.0,500.0,5,9,2019,10,55,5,9,2019,19,15